package DSP;
global java.util.List list;

rule "dsp_rules_318"
    when
      	m:Message(point_name=="aciPOW-REAPOW"&& type =="MIT"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"MIT\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_317"
    when
      	m:Message(point_name=="aciPOW-ACTPOW"&& type =="MIT"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"MIT\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_316"
    when
      	m:Message(point_name=="aciPOW-REAPOW"&& type =="MIT"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"MIT\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_315"
    when
      	m:Message(point_name=="aciPOW-ACTPOW"&& type =="MIT"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"MIT\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_314"
    when
      	m:Message(point_name=="aciPOW-REAPOW"&& type =="MIT"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"MIT\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_313"
    when
      	m:Message(point_name=="aciPOW-ACTPOW"&& type =="MIT"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"MIT\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_312"
    when
      	m:Message(point_name=="aciPOW-REAPOW"&& type =="MIT"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"MIT\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_311"
    when
      	m:Message(point_name=="aciPOW-ACTPOW"&& type =="MIT"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"MIT\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_310"
    when
      	m:Message(point_name=="aciPOW-REAPOW"&& type =="MIT"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"MIT\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_309"
    when
      	m:Message(point_name=="aciPOW-ACTPOW"&& type =="MIT"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"MIT\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_308"
    when
      	m:Message(point_name=="aciPOW-REAPOW"&& type =="MIT"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"MIT\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_307"
    when
      	m:Message(point_name=="aciPOW-ACTPOW"&& type =="MIT"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"MIT\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_306"
    when
      	m:Message(point_name=="aciPOW-REAPOW"&& type =="MIT"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"MIT\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_305"
    when
      	m:Message(point_name=="aciPOW-ACTPOW"&& type =="MIT"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"MIT\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_304"
    when
      	m:Message(point_name=="aciPOW-REAPOW"&& type =="MIT"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"MIT\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_303"
    when
      	m:Message(point_name=="aciPOW-ACTPOW"&& type =="MIT"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"MIT\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_302"
    when
      	m:Message(point_name=="aciPOW-ACTPOW"&& type =="MIT"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"MIT\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_301"
    when
      	m:Message(point_name=="aciPOW-REAPOW"&& type =="MIT"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"MIT\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_300"
    when
      	m:Message(point_name=="aciPOW-ACTPOW"&& type =="MIT"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"MIT\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_299"
    when
      	m:Message(point_name=="aciPOW-REAPOW"&& type =="MIT"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"MIT\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_298"
    when
      	m:Message(point_name=="aciPOW-REAPOWN"&& type =="AI"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_297"
    when
      	m:Message(point_name=="aciPOW-REAPOWP"&& type =="AI"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_296"
    when
      	m:Message(point_name=="aciPOW-ACTPOWN"&& type =="AI"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_295"
    when
      	m:Message(point_name=="aciPOW-ACTPOWP"&& type =="AI"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_294"
    when
      	m:Message(point_name=="aciPOW-REAPOWN"&& type =="AI"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_293"
    when
      	m:Message(point_name=="aciPOW-REAPOWP"&& type =="AI"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_292"
    when
      	m:Message(point_name=="aciPOW-ACTPOWN"&& type =="AI"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_291"
    when
      	m:Message(point_name=="aciPOW-ACTPOWP"&& type =="AI"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_290"
    when
      	m:Message(point_name=="aciPOW-CURRENTIC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_289"
    when
      	m:Message(point_name=="aciPOW-CURRENTIB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_288"
    when
      	m:Message(point_name=="aciPOW-CURRENTIA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_287"
    when
      	m:Message(point_name=="aciPOW-POWFCT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_286"
    when
      	m:Message(point_name=="aciPOW-VOLTSQ"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_285"
    when
      	m:Message(point_name=="aciPOW-VOLTSP"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_284"
    when
      	m:Message(point_name=="aciPOW-VOLTUC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_283"
    when
      	m:Message(point_name=="aciPOW-VOLTUB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_282"
    when
      	m:Message(point_name=="aciPOW-VOLTUA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_281"
    when
      	m:Message(point_name=="aciPOW-FREQZ"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_280"
    when
      	m:Message(point_name=="aciPOW-REAPOWN"&& type =="AI"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_279"
    when
      	m:Message(point_name=="aciPOW-REAPOWP"&& type =="AI"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_278"
    when
      	m:Message(point_name=="aciPOW-ACTPOWN"&& type =="AI"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_277"
    when
      	m:Message(point_name=="aciPOW-ACTPOWP"&& type =="AI"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_276"
    when
      	m:Message(point_name=="aciPOW-POWFCT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_275"
    when
      	m:Message(point_name=="aciPOW-NOVOLT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_274"
    when
      	m:Message(point_name=="aciPOW-VOLTPOW"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_273"
    when
      	m:Message(point_name=="aciPOW-ZESECNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_272"
    when
      	m:Message(point_name=="aciPOW-PHACCNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_271"
    when
      	m:Message(point_name=="aciPOW-PHABCNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_270"
    when
      	m:Message(point_name=="aciPOW-PHAACNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_269"
    when
      	m:Message(point_name=="N/A"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_268"
    when
      	m:Message(point_name=="N/A"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_267"
    when
      	m:Message(point_name=="N/A"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_266"
    when
      	m:Message(point_name=="aciPOW-REAPOWN"&& type =="AI"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_265"
    when
      	m:Message(point_name=="aciPOW-REAPOWP"&& type =="AI"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_264"
    when
      	m:Message(point_name=="aciPOW-ACTPOWN"&& type =="AI"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_263"
    when
      	m:Message(point_name=="aciPOW-ACTPOWP"&& type =="AI"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_262"
    when
      	m:Message(point_name=="aciPOW-REAPOWN"&& type =="AI"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_261"
    when
      	m:Message(point_name=="aciPOW-REAPOWP"&& type =="AI"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_260"
    when
      	m:Message(point_name=="aciPOW-ACTPOWN"&& type =="AI"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_259"
    when
      	m:Message(point_name=="aciPOW-ACTPOWP"&& type =="AI"&&((value>=4294967295)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"4294967295\"}");
end

rule "dsp_rules_258"
    when
      	m:Message(point_name=="aciPOW-CURRENTUIC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_257"
    when
      	m:Message(point_name=="aciPOW-CURRENTUIB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_256"
    when
      	m:Message(point_name=="aciPOW-CURRENTUIA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_255"
    when
      	m:Message(point_name=="aciPOW-VOLTUCA2"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_254"
    when
      	m:Message(point_name=="aciPOW-VOLTUBC2"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_253"
    when
      	m:Message(point_name=="aciPOW-VOLTUAB2"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_252"
    when
      	m:Message(point_name=="aciPOW-VOLT3U02"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_251"
    when
      	m:Message(point_name=="aciPOW-VOLTUC2"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_250"
    when
      	m:Message(point_name=="aciPOW-VOLTUB2"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_249"
    when
      	m:Message(point_name=="aciPOW-VOLTUA2"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_248"
    when
      	m:Message(point_name=="aciPOW-KVOLTUCA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_247"
    when
      	m:Message(point_name=="aciPOW-KVOLTUBC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_246"
    when
      	m:Message(point_name=="aciPOW-KVOLTUAB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_245"
    when
      	m:Message(point_name=="aciPOW-TRIVOLT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_244"
    when
      	m:Message(point_name=="aciPOW-KVOLTUC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_243"
    when
      	m:Message(point_name=="aciPOW-KVOLTUB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_242"
    when
      	m:Message(point_name=="aciPOW-KVOLTUA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_241"
    when
      	m:Message(point_name=="aciPOW-POWFCT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_240"
    when
      	m:Message(point_name=="aciPOW-VOLTSQ"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_239"
    when
      	m:Message(point_name=="aciPOW-VOLTSP"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_238"
    when
      	m:Message(point_name=="aciPOW-CURRENTT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_237"
    when
      	m:Message(point_name=="aciPOW-CURRENTIC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_236"
    when
      	m:Message(point_name=="aciPOW-CURRENTIB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_235"
    when
      	m:Message(point_name=="aciPOW-CURRENTIA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_234"
    when
      	m:Message(point_name=="aciPOW-KVOLTUCA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_233"
    when
      	m:Message(point_name=="aciPOW-KVOLTUBC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_232"
    when
      	m:Message(point_name=="aciPOW-KVOLTUAB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_231"
    when
      	m:Message(point_name=="aciPOW-TRIVOLT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_230"
    when
      	m:Message(point_name=="aciPOW-KVOLTUC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_229"
    when
      	m:Message(point_name=="aciPOW-KVOLTUB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_228"
    when
      	m:Message(point_name=="aciPOW-KVOLTUA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_227"
    when
      	m:Message(point_name=="aciPOW-POWFCT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_226"
    when
      	m:Message(point_name=="aciPOW-VOLTSQ"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_225"
    when
      	m:Message(point_name=="aciPOW-VOLTSP"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_224"
    when
      	m:Message(point_name=="aciPOW-CURRENTT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_223"
    when
      	m:Message(point_name=="aciPOW-CURRENTIC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_222"
    when
      	m:Message(point_name=="aciPOW-CURRENTIB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_221"
    when
      	m:Message(point_name=="aciPOW-CURRENTIA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_220"
    when
      	m:Message(point_name=="aciPOW-KVOLTUCA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_219"
    when
      	m:Message(point_name=="aciPOW-KVOLTUBC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_218"
    when
      	m:Message(point_name=="aciPOW-KVOLTUAB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_217"
    when
      	m:Message(point_name=="aciPOW-TRIVOLT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_216"
    when
      	m:Message(point_name=="aciPOW-KVOLTUC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_215"
    when
      	m:Message(point_name=="aciPOW-KVOLTUB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_214"
    when
      	m:Message(point_name=="aciPOW-KVOLTUA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_213"
    when
      	m:Message(point_name=="aciPOW-SETREG"&& type =="AI"&&((value>=32767)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_212"
    when
      	m:Message(point_name=="aciPOW-SETREG"&& type =="AI"&&((value>=32767)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_211"
    when
      	m:Message(point_name=="aciPOW-FREQZ"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_210"
    when
      	m:Message(point_name=="aciPOW-POWFCT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_209"
    when
      	m:Message(point_name=="aciPOW-VOLTSQ"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_208"
    when
      	m:Message(point_name=="aciPOW-VOLTSP"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_207"
    when
      	m:Message(point_name=="aciPOW-KVOLTUCA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_206"
    when
      	m:Message(point_name=="aciPOW-KVOLTUBC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_205"
    when
      	m:Message(point_name=="aciPOW-KVOLTUAB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_204"
    when
      	m:Message(point_name=="aciPOW-KVOLTUX"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_203"
    when
      	m:Message(point_name=="aciPOW-KVOLTUC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_202"
    when
      	m:Message(point_name=="aciPOW-KVOLTUB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_201"
    when
      	m:Message(point_name=="aciPOW-KVOLTUA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_200"
    when
      	m:Message(point_name=="aciPOW-CURRENTIC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_199"
    when
      	m:Message(point_name=="aciPOW-CURRENTIB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_198"
    when
      	m:Message(point_name=="aciPOW-CURRENTIA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_197"
    when
      	m:Message(point_name=="aciPOW-SETREG"&& type =="AI"&&((value>=32767)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_196"
    when
      	m:Message(point_name=="aciPOW-POWFCT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_195"
    when
      	m:Message(point_name=="aciPOW-VOLTSQ"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_194"
    when
      	m:Message(point_name=="aciPOW-VOLTSP"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_193"
    when
      	m:Message(point_name=="aciPOW-CURRENTT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_192"
    when
      	m:Message(point_name=="aciPOW-CURRENTIC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_191"
    when
      	m:Message(point_name=="aciPOW-CURRENTIB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_190"
    when
      	m:Message(point_name=="aciPOW-CURRENTIA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_189"
    when
      	m:Message(point_name=="aciPOW-KVOLTUCA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_188"
    when
      	m:Message(point_name=="aciPOW-KVOLTUBC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_187"
    when
      	m:Message(point_name=="aciPOW-KVOLTUAB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_186"
    when
      	m:Message(point_name=="aciPOW-TRIVOLT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_185"
    when
      	m:Message(point_name=="aciPOW-KVOLTUC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_184"
    when
      	m:Message(point_name=="aciPOW-KVOLTUB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_183"
    when
      	m:Message(point_name=="aciPOW-KVOLTUA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_182"
    when
      	m:Message(point_name=="aciPOW-POS"&& type =="AI"&&((value>=32767)||(value<=0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_181"
    when
      	m:Message(point_name=="aciPOW-TEMPLN"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_180"
    when
      	m:Message(point_name=="aciPOW-OILTEMP2"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_179"
    when
      	m:Message(point_name=="aciPOW-OILTEMP1"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_178"
    when
      	m:Message(point_name=="aciPOW-POWFCT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_177"
    when
      	m:Message(point_name=="aciPOW-VOLTSQ"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_176"
    when
      	m:Message(point_name=="aciPOW-VOLTSP"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_175"
    when
      	m:Message(point_name=="aciPOW-CURRENTT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_174"
    when
      	m:Message(point_name=="aciPOW-CURRENTIC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_173"
    when
      	m:Message(point_name=="aciPOW-CURRENTIB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_172"
    when
      	m:Message(point_name=="aciPOW-CURRENTIA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_171"
    when
      	m:Message(point_name=="aciPOW-KVOLTUCA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_170"
    when
      	m:Message(point_name=="aciPOW-KVOLTUBC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_169"
    when
      	m:Message(point_name=="aciPOW-KVOLTUAB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_168"
    when
      	m:Message(point_name=="aciPOW-TRIVOLT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_167"
    when
      	m:Message(point_name=="aciPOW-KVOLTUC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_166"
    when
      	m:Message(point_name=="aciPOW-KVOLTUB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_165"
    when
      	m:Message(point_name=="aciPOW-KVOLTUA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_164"
    when
      	m:Message(point_name=="aciPOW-POWFCT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_163"
    when
      	m:Message(point_name=="aciPOW-NOVOLT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_162"
    when
      	m:Message(point_name=="aciPOW-VOLTPOW"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_161"
    when
      	m:Message(point_name=="aciPOW-CURRENTT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_160"
    when
      	m:Message(point_name=="aciPOW-CURRENTIC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_159"
    when
      	m:Message(point_name=="aciPOW-CURRENTIB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_158"
    when
      	m:Message(point_name=="aciPOW-CURRENTIA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_157"
    when
      	m:Message(point_name=="aciPOW-KVOLTUCA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_156"
    when
      	m:Message(point_name=="aciPOW-KVOLTUBC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_155"
    when
      	m:Message(point_name=="aciPOW-KVOLTUAB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_154"
    when
      	m:Message(point_name=="aciPOW-TRIVOLT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_153"
    when
      	m:Message(point_name=="aciPOW-KVOLTUC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_152"
    when
      	m:Message(point_name=="aciPOW-KVOLTUB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_151"
    when
      	m:Message(point_name=="aciPOW-KVOLTUA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_150"
    when
      	m:Message(point_name=="aciPOW-DCVCA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_149"
    when
      	m:Message(point_name=="aciPOW-DCVBC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_148"
    when
      	m:Message(point_name=="aciPOW-DCVAB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_147"
    when
      	m:Message(point_name=="aciPOW-RESISTN2"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_146"
    when
      	m:Message(point_name=="aciPOW-RESISTP2"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_145"
    when
      	m:Message(point_name=="aciPOW-BUSVDC2"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_144"
    when
      	m:Message(point_name=="aciPOW-RESISTN1"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_143"
    when
      	m:Message(point_name=="aciPOW-RESISTP1"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_142"
    when
      	m:Message(point_name=="aciPOW-ENVCNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_141"
    when
      	m:Message(point_name=="aciPOW-TEMP"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_140"
    when
      	m:Message(point_name=="aciPOW-BATTCNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_139"
    when
      	m:Message(point_name=="aciPOW-BATTVOLT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_138"
    when
      	m:Message(point_name=="aciPOW-RECIOUT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_137"
    when
      	m:Message(point_name=="aciPOW-RECVOUT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_136"
    when
      	m:Message(point_name=="aciPOW-BUSVDC1"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_135"
    when
      	m:Message(point_name=="aciPOW-ARCVOLT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_134"
    when
      	m:Message(point_name=="aciPOW-ISOVOLT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_133"
    when
      	m:Message(point_name=="aciPOW-ARCCNT2"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_132"
    when
      	m:Message(point_name=="aciPOW-ARCCNT1"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_131"
    when
      	m:Message(point_name=="aciPOW-RESERVE"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_130"
    when
      	m:Message(point_name=="aciPOW-DIOCNT6"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_129"
    when
      	m:Message(point_name=="aciPOW-DIOCNT5"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_128"
    when
      	m:Message(point_name=="aciPOW-DIOCNT4"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_127"
    when
      	m:Message(point_name=="aciPOW-DIOCNT3"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_126"
    when
      	m:Message(point_name=="aciPOW-DIOCNT2"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_125"
    when
      	m:Message(point_name=="aciPOW-DIOCNT1"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_124"
    when
      	m:Message(point_name=="aciPOW-VOLTD"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_123"
    when
      	m:Message(point_name=="aciPOW-VOLTU"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_122"
    when
      	m:Message(point_name=="aciPOW-DRAIND"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_121"
    when
      	m:Message(point_name=="aciPOW-DRAINU"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_120"
    when
      	m:Message(point_name=="aciPOW-CURRENT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_119"
    when
      	m:Message(point_name=="aciPOW-VOLTAGE"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_118"
    when
      	m:Message(point_name=="aciPOW-TEMP"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_117"
    when
      	m:Message(point_name=="aciPOW-PHCTEMP"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_116"
    when
      	m:Message(point_name=="aciPOW-PHBTEMP"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_115"
    when
      	m:Message(point_name=="aciPOW-PHATEMP"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_114"
    when
      	m:Message(point_name=="aciPOW-TEMP"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_113"
    when
      	m:Message(point_name=="aciPOW-PHCTEMP"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_112"
    when
      	m:Message(point_name=="aciPOW-PHBTEMP"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_111"
    when
      	m:Message(point_name=="aciPOW-PHATEMP"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_110"
    when
      	m:Message(point_name=="aciPOW-TEMP"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_109"
    when
      	m:Message(point_name=="aciPOW-CURRENTIC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_108"
    when
      	m:Message(point_name=="aciPOW-CURRENTIB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_107"
    when
      	m:Message(point_name=="aciPOW-CURRENTIA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_106"
    when
      	m:Message(point_name=="aciPOW-POWFCT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_105"
    when
      	m:Message(point_name=="aciPOW-VOLTSQ"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_104"
    when
      	m:Message(point_name=="aciPOW-VOLTSP"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_103"
    when
      	m:Message(point_name=="aciPOW-VOLTUC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_102"
    when
      	m:Message(point_name=="aciPOW-VOLTUB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_101"
    when
      	m:Message(point_name=="aciPOW-VOLTUA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_100"
    when
      	m:Message(point_name=="aciPOW-FREQZ"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_99"
    when
      	m:Message(point_name=="aciPOW-FDCNTIC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_98"
    when
      	m:Message(point_name=="aciPOW-FDCNTIB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_97"
    when
      	m:Message(point_name=="aciPOW-FDCNTIA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_96"
    when
      	m:Message(point_name=="aciPOW-FDCNTIC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_95"
    when
      	m:Message(point_name=="aciPOW-FDCNTIB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_94"
    when
      	m:Message(point_name=="aciPOW-FDCNTIA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_93"
    when
      	m:Message(point_name=="aciPOW-FDCNTIC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_92"
    when
      	m:Message(point_name=="aciPOW-FDCNTIB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_91"
    when
      	m:Message(point_name=="aciPOW-FDCNTIA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_90"
    when
      	m:Message(point_name=="aciPOW-CURRENTIC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_89"
    when
      	m:Message(point_name=="aciPOW-CURRENTIB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_88"
    when
      	m:Message(point_name=="aciPOW-CURRENTIA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_87"
    when
      	m:Message(point_name=="aciPOW-BUSCNTIC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_86"
    when
      	m:Message(point_name=="aciPOW-BUSCNTIB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_85"
    when
      	m:Message(point_name=="aciPOW-BUSCNTIA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_84"
    when
      	m:Message(point_name=="aciPOW-CURRENTIC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_83"
    when
      	m:Message(point_name=="aciPOW-CURRENTIB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_82"
    when
      	m:Message(point_name=="aciPOW-CURRENTIA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_81"
    when
      	m:Message(point_name=="aciPOW-POWFCT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_80"
    when
      	m:Message(point_name=="aciPOW-VOLTSQ"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_79"
    when
      	m:Message(point_name=="aciPOW-VOLTSP"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_78"
    when
      	m:Message(point_name=="aciPOW-VOLTUC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_77"
    when
      	m:Message(point_name=="aciPOW-VOLTUB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_76"
    when
      	m:Message(point_name=="aciPOW-VOLTUA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_75"
    when
      	m:Message(point_name=="aciPOW-FREQZ"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_74"
    when
      	m:Message(point_name=="aciPOW-RNTCNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_73"
    when
      	m:Message(point_name=="aciPOW-VOLTAGE"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_72"
    when
      	m:Message(point_name=="aciPOW-CURRENT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_71"
    when
      	m:Message(point_name=="aciPOW-NEGCNT2"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_70"
    when
      	m:Message(point_name=="aciPOW-NEGCNT1"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_69"
    when
      	m:Message(point_name=="aciPOW-BGVOLTN"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_68"
    when
      	m:Message(point_name=="aciPOW-CURRENT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_67"
    when
      	m:Message(point_name=="aciPOW-VOLTAGE"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_66"
    when
      	m:Message(point_name=="aciPOW-INCNT1"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_65"
    when
      	m:Message(point_name=="aciPOW-BUSVOLT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_64"
    when
      	m:Message(point_name=="aciPOW-POWFCT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_63"
    when
      	m:Message(point_name=="aciPOW-NOVOLT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_62"
    when
      	m:Message(point_name=="aciPOW-VOLTPOW"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_61"
    when
      	m:Message(point_name=="aciPOW-ZESECNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_60"
    when
      	m:Message(point_name=="aciPOW-PHACCNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_59"
    when
      	m:Message(point_name=="aciPOW-PHABCNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_58"
    when
      	m:Message(point_name=="aciPOW-PHAACNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_57"
    when
      	m:Message(point_name=="aciPOW-POWFCT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_56"
    when
      	m:Message(point_name=="aciPOW-NOVOLT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_55"
    when
      	m:Message(point_name=="aciPOW-VOLTPOW"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_54"
    when
      	m:Message(point_name=="aciPOW-ZESECNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_53"
    when
      	m:Message(point_name=="aciPOW-PHACCNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_52"
    when
      	m:Message(point_name=="aciPOW-PHABCNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_51"
    when
      	m:Message(point_name=="aciPOW-PHAACNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_50"
    when
      	m:Message(point_name=="aciPOW-ZESECNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_49"
    when
      	m:Message(point_name=="aciPOW-PHACCNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_48"
    when
      	m:Message(point_name=="aciPOW-PHABCNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_47"
    when
      	m:Message(point_name=="aciPOW-PHAACNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_46"
    when
      	m:Message(point_name=="aciPOW-POWFCT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_45"
    when
      	m:Message(point_name=="aciPOW-NOVOLT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_44"
    when
      	m:Message(point_name=="aciPOW-VOLTPOW"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_43"
    when
      	m:Message(point_name=="aciPOW-VOLTUC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_42"
    when
      	m:Message(point_name=="aciPOW-VOLTUB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_41"
    when
      	m:Message(point_name=="aciPOW-VOLTUA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_40"
    when
      	m:Message(point_name=="aciPOW-VOLTUCAI"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_39"
    when
      	m:Message(point_name=="aciPOW-VOLTUBCI"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_38"
    when
      	m:Message(point_name=="aciPOW-VOLTUABI"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_37"
    when
      	m:Message(point_name=="aciPOW-ZESECNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_36"
    when
      	m:Message(point_name=="aciPOW-PHACCNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_35"
    when
      	m:Message(point_name=="aciPOW-PHABCNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_34"
    when
      	m:Message(point_name=="aciPOW-PHAACNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_33"
    when
      	m:Message(point_name=="aciPOW-POWFCT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_32"
    when
      	m:Message(point_name=="aciPOW-NOVOLT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_31"
    when
      	m:Message(point_name=="aciPOW-VOLTPOW"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_30"
    when
      	m:Message(point_name=="aciPOW-VOLTUC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_29"
    when
      	m:Message(point_name=="aciPOW-VOLTUB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_28"
    when
      	m:Message(point_name=="aciPOW-VOLTUA"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_27"
    when
      	m:Message(point_name=="aciPOW-VOLTUCAI"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_26"
    when
      	m:Message(point_name=="aciPOW-VOLTUBCI"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_25"
    when
      	m:Message(point_name=="aciPOW-VOLTUABI"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_24"
    when
      	m:Message(point_name=="aciPOW-ZESECNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_23"
    when
      	m:Message(point_name=="aciPOW-PHACCNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_22"
    when
      	m:Message(point_name=="aciPOW-PHABCNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_21"
    when
      	m:Message(point_name=="aciPOW-PHAACNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_20"
    when
      	m:Message(point_name=="aciPOW-DCAC2AC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_19"
    when
      	m:Message(point_name=="aciPOW-DCAC2BC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_18"
    when
      	m:Message(point_name=="aciPOW-DCAC2AB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_17"
    when
      	m:Message(point_name=="aciPOW-DCAC1AC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_16"
    when
      	m:Message(point_name=="aciPOW-DCAC1BC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_15"
    when
      	m:Message(point_name=="aciPOW-DCAC1AB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_14"
    when
      	m:Message(point_name=="aciPOW-ACAC2AC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_13"
    when
      	m:Message(point_name=="aciPOW-ACAC2BC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_12"
    when
      	m:Message(point_name=="aciPOW-ACAC2AB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_11"
    when
      	m:Message(point_name=="aciPOW-ACAC1AC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_10"
    when
      	m:Message(point_name=="aciPOW-ACAC1BC"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_9"
    when
      	m:Message(point_name=="aciPOW-ACAC1AB"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_8"
    when
      	m:Message(point_name=="aciPOW-BGVOLTP"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_7"
    when
      	m:Message(point_name=="aciPOW-BGVOLTN"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_6"
    when
      	m:Message(point_name=="aciPOW-ENVCNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_5"
    when
      	m:Message(point_name=="aciPOW-BATTCNT"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_4"
    when
      	m:Message(point_name=="aciPOW-BUSVOLT1"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_3"
    when
      	m:Message(point_name=="aciPOW-BUSCNT1"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_2"
    when
      	m:Message(point_name=="aciPOW-BUSVOLT2"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end

rule "dsp_rules_1"
    when
      	m:Message(point_name=="aciPOW-BUSCNT2"&& type =="AI"&&((value>=32767)||(value<=-32767.0)))
    then
    	list.add("{\"point_name\":\""+m.point_name+"\",\"value\":\""+m.value+"\",\"acquisitionTime\":\""+m.acquisitionTime+"\",\"type\":\"AI\",\"alarm_sub\":\"-32767.0\",\"alarm_sup\":\"32767\"}");
end


